#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
#mpDris2 &
#udiskie &
picom -b

~/.fehbg &
# nm-applet &
setxkbmap -layout us -variant altgr-intl &

bspc monitor LVDS1 -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI-1 -d IX X

bspc config border_width         2
bspc config window_gap           4
bspc config normal_border_color "#565f89"
bspc config focused_border_color "#2ac3de"
bspc config urgent_border_color "#f7768e"
bspc config presel_border_color "#26E2FF"

bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc rule -a KeePassXC desktop='^8' state=tiled
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Emacs state=tiled follow=on
bspc rule -a Zathura state=tiled
